remote: origin
target-branch: master
helm-extra-args: --timeout 600s
chart-yaml-schema: .github/chart_schema.yaml
chart-repos:
- truecharts=https://truecharts.org
- bitnami=https://charts.bitnami.com/bitnami
- amd-gpu-helm=https://radeonopencompute.github.io/k8s-device-plugin/
SkipExisting: true
