image:
  repository: tccr.io/truecharts/onlyoffice-ds
  tag: v7.0.0@sha256:957599910369a83815b4529d65e1eef41b8eac33eed98da6be33bd80f7464512
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secret:
  JWT_SECRET: "randomgeneratedstring"

env:
  WOPI_ENABLED: true
  JWT_ENABLED: true
  DB_TYPE: "postgres"
  DB_PORT: 5432
  DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  REDIS_SERVER_PORT: 6379

envValueFrom:
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DB_PWD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  REDIS_SERVER_HOST:
    secretKeyRef:
      name: rediscreds
      key: url

service:
  main:
    ports:
      main:
        port: 10043
        targetPort: 80

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: onlyoffice
  postgresqlDatabase: onlyoffice

# Enabled redis
redis:
  enabled: true
  existingSecret: "rediscreds"
